#  application.yaml работает в jvm и native, но не работает в режиме сервлета с Tomcat
# в этом случае необходимо сформировать application.conf

ktor:
  development: true
  deployment:
    port: 8080
  watch:
    - classes
    - resources
  application:
    modules:
      - "ru.otus.crowd.proj.docs.cards.app.ktor.ApplicationKt.module"
  #  urls:
  #    - "http://127.0.0.1:8080/v1"
  #    - "http://0.0.0.0:8080/v1"
  #    - "http://192.168.0.182:8080/v1"
  logger: kmp

  marketplace:
    repository:
      test: "inmemory"
      prod: "$DB_TYPE_PROD:inmemory"
      psql:
        schema: public
        database: "$MKPL_DOC_CARDS_DB:mk_plc_doc_cards"
        host: "$MKPL_DOC_CARDS_HOST:localhost"
        port: "$MKPL_DOC_CARDS_PORT:5432"
        user: "$MKPL_DOC_CARDS_USER:postgres"
        password: "$MKPL_DOC_CARDS_PASS:marketplace-pass"